In [3]:
import numpy as np

### Basic Array Creation

In [8]:
# Array Creation
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [12]:
# List Creation
list=[1,2,3,4,"Akash","Singh"]
list

list1=[[1,2,3],[4,5,6],[7,8,9]]
list1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
# Type Conversion
# Change the Data into String format.
np.array(list)
np.array(list1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Generation Function

In [16]:
# Generate the Array.
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# Generate the Zeros Array.
arr=np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# Generate the Ones Array.
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [23]:
# Generate the Number but give the linear spacing of given interval.
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Random Generation Function

In [26]:
arr=np.random.rand(10)
arr

array([0.46614767, 0.54947621, 0.50647877, 0.13345734, 0.92255207,
       0.36174085, 0.95607002, 0.87453354, 0.74755174, 0.62271643])

In [27]:
arr=np.random.randn(10)
arr

array([ 0.36640719,  1.21632854, -0.20297566,  0.55284905, -0.79256132,
       -0.36229553,  0.13457344, -0.40774556,  0.26857014,  1.04951115])

In [29]:
arr=np.random.randint(10,20,5)
arr

array([19, 14, 15, 13, 15])

### Array Attributes

In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# Give the Shape of Array
# Return the Number of Rows and Column.
arr.shape

(3, 3)

In [34]:
# Return the Size of the Array.
arr.size

9

In [36]:
# Return the Datatype
arr.dtype

dtype('int64')

### Array Method

In [39]:
# Return the Minimum number in this Array
arr.min()

np.int64(1)

In [40]:
# Return the Maximum Number in this Array
arr.max()

np.int64(9)

In [42]:
# Give the Sum of all this Number
arr.sum()

np.int64(45)

In [44]:
# Give the Sum of all this Number using Column Axis.
np.sum(arr, axis=0)

# Give the Sum of all this Number using Row Axis.
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [45]:
# Return the Mean of this Number.
arr.mean()

np.float64(5.0)

In [46]:
# Return the Standard Deviation.
arr.std()

np.float64(2.581988897471611)

In [47]:
arr.argmax()

np.int64(8)

In [48]:
arr.argmin()

np.int64(0)

### Reshaping And Resizing

In [50]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Numpy Indexing and Slicing Vectors

In [53]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
# Indexing
# Return the Number Present in this Index.
# Accessing individual elements in a NumPy array using their position (index).
arr[6]

np.int64(17)

In [57]:
# Slicing
# Return the Multi Number.
# Access a range of elements using start:end:step.
arr[1:6]

array([12, 13, 14, 15, 16])

In [60]:
arr[1::2]

array([12, 14, 16, 18, 20])

## Numpy Indexing and Slicing of Matrix

In [63]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
# Indexing
# Use row, column format → mat[row][col] or mat[row, col]
arr[0]

array([1, 2, 3, 4, 5])

In [67]:
# Slicing
# Use : to get ranges of rows/columns → mat[row_start:row_end, col_start:col_end]
slice=arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

## Array Operation

### Arithmatic Operations

In [73]:
# Arithmetic operations in NumPy work element by element and make calculations faster and easier.
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
# a1 + a2
# a1-a2
a1*a2
a1/a2
a1//a2
a1**a2

array([    1,    64,  2187, 65536])

### Broadcasting

In [74]:
# Broadcasting means automatically matching array shapes so that arithmetic operations can be done without writing loops.

l=[10,20,30,40,50]
arr=np.array(l)
arr+10

array([20, 30, 40, 50, 60])

### Deep and Shallow Copy

In [75]:
# Shallow:
    # Creates a new object, but does not copy the actual data.
    # Both the original and the copy share the same data in memory.
    # Changing one will affect the other.



In [76]:
# Deep:
    # Creates a new object and copies all data separately.
    # Both arrays are independent — changing one won’t affect the other.



In [79]:
# Matrix operations in NumPy include addition, subtraction, multiplication, transpose, inverse, and determinant, used for linear algebra and data computation.

a=np.array([[1,2],[3,4]])
b=np.array([[6,7],[8,9]])

# Multiplication of this matrix
a@b
# np.dot(a,b)

array([[22, 25],
       [50, 57]])

In [80]:
# Transpose Matrix
a.T

array([[1, 3],
       [2, 4]])

### Advance Array Operations

#### Stacking

In [82]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [83]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Splitting Array

In [86]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
np.split(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [88]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Exercise

In [ ]:
# columns: [Age,Math Marks, Science Marks]
data=np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 95],
    [18, 65, 70],
    [20, 90, 85]
])